### PR TITLE
Graphics proposition + mod icon + fr

### PR DESCRIPTION
**Pull request by snouz**
<a href="https://imgur.com/5QQYYST"></a>

### CODE REVIEW

**Comment by 0ptera** [comment]
The new graphics look nice.

I'm not happy with the thumbnail:
- Floating text looks out of place and isn't necessary in the first place. The picture of a chest with visible incinerator should be enough.
- Black holes never have radial features. If you want a stylized simplified depiction look at Stellaris for example: https://pbs.twimg.com/media/CfdVGIXWQAAqcSz?format=jpg&name=small

Generally I don't accept localization I can't maintain myself, but since this mod is so simplistic I'll make an exception.

Please leave editing info and changelog to me.

**Comment by snouz** [comment]
Ok, removing the text.
For the background, it wasn't meant to be a black hole, just an artistic interpretation of emptiness, which I think looks neat.
Replacing with a black hole if you prefer.

**Comment by 0ptera** [comment]
I don't really want a black hole either, perhaps just the chest will do.

**Comment by 0ptera** [comment]
I could not find nega in either google or dict.cc.
Both translate void with annuler or vide.

**Comment by snouz** [comment]
Annuler = to cancel (as in "to void a contract")

I am a native french speaker, I'll explain. Nega is a prefix that is the abbreviation of négatif.
I came to this translation because in French, void doesn't really translate well, vide means empty, le vide means emptiness, so "coffre du vide" would mean chest of emptiness, "coffre de vide" would mean chest [made of] emptiness, coffre vide means empty chest.

There's also Anti-coffre, but it would also mean "against chests". Coffre du néant sounds badass but also more like a boss or a legendary item in a rpg

In the end, nega chest sounds (in french) as badass as void chest, it's a generally understood prefix that comes from latin https://fr.wiktionary.org/wiki/n%C3%A9gatif , it feels like the correct tone for it, it conveys the idea of "opposite" as well as "mega-chest" would convey the idea of gigantism.

**Comment by 0ptera** [comment]
Thanks for clarifying. As native German speaker it sounded like racial slur to me.
Funny side note: https://minecraft-archive.fandom.com/fr/wiki/Coffre_du_n%C3%A9ant

**Pull request merged**
